files:
  - source: /Resources/Private/Language/
    translation: /Resources/Private/Language/%two_letters_code%.locallang.xlf
    ignore:
      - /Resources/Private/Language/de.*
      - /Resources/Private/Language/cs.*
      - /Resources/Private/Language/pl.*
      - /Resources/Private/Language/ru.*
      - /Resources/Private/Language/zh.*
  - source: /Resources/Private/Language/
    translation: /Resources/Private/Language/%two_letters_code%.locallang_be.xlf
    ignore:
      - /Resources/Private/Language/de.*
      - /Resources/Private/Language/cs.*
      - /Resources/Private/Language/pl.*
      - /Resources/Private/Language/ru.*
      - /Resources/Private/Language/zh.*
  - source: /Resources/Private/Language/
    translation: /Resources/Private/Language/%two_letters_code%.locallang_csh.xlf
    ignore:
      - /Resources/Private/Language/de.*
      - /Resources/Private/Language/de.*
      - /Resources/Private/Language/cs.*
      - /Resources/Private/Language/pl.*
      - /Resources/Private/Language/ru.*
      - /Resources/Private/Language/zh.*
  - source: /Resources/Private/Language/
    translation: /Resources/Private/Language/%two_letters_code%.locallang_db.xlf
    ignore:
      - /Resources/Private/Language/de.*
      - /Resources/Private/Language/cs.*
      - /Resources/Private/Language/pl.*
      - /Resources/Private/Language/ru.*
      - /Resources/Private/Language/zh.*
