# Configuration/Services.yaml
services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Evoweb\StoreFinder\:
    resource: '../Classes/*'

  cache.store_finder.coordinate_cache:
    class: 'TYPO3\CMS\Core\Cache\Frontend\FrontendInterface'
    factory: ['@TYPO3\CMS\Core\Cache\CacheManager', 'getCache']
    arguments:
      $identifier: 'store_finder_coordinate_cache'
    public: true

  SJBR\StaticInfoTables\Domain\Repository\TerritoryRepository:
    public: true

  SJBR\StaticInfoTables\Domain\Repository\CountryZoneRepository:
    public: true
