# Configuration/Services.yaml
services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Evoweb\StoreFinder\:
    resource: '../Classes/*'

  cache.store_finder.coordinate_cache:
    class: 'TYPO3\CMS\Core\Cache\Frontend\FrontendInterface'
    factory: ['@TYPO3\CMS\Core\Cache\CacheManager', 'getCache']
    arguments:
      $identifier: 'store_finder_coordinate_cache'
    public: true

  frontend.user:
    class: 'TYPO3\CMS\Core\Cache\Frontend\FrontendInterface'
    factory: ['@Evoweb\StoreFinder\Service\FrontendUserService', 'getCurrentUser']
    public: true

  Evoweb\StoreFinder\Cache\CoordinatesCache:
    arguments:
      $cacheFrontend: '@cache.store_finder.coordinate_cache'
    public: true

  Evoweb\StoreFinder\Command\ImportLocationsCommand:
    tags:
      - name: 'console.command'
        command: 'storefinder:import'
        description: 'Import locations from excel file into given storage folder (default 1)'
        schedulable: true

  Evoweb\StoreFinder\Command\GeocodeLocationsCommand:
    tags:
      - name: 'console.command'
        command: 'storefinder:geocode'
        description: 'Query google geocode service to get lat/lon for locations that are not geocode already'
        schedulable: true

  Evoweb\StoreFinder\Domain\Repository\CategoryRepository:
    public: true

  Evoweb\StoreFinder\Domain\Repository\ContentRepository:
    public: true

  Evoweb\StoreFinder\Domain\Repository\LocationRepository:
    public: true

  Evoweb\StoreFinder\Domain\Repository\CountryRepository:
    public: true

  Evoweb\StoreFinder\Hooks\TcaItemsProcessorFunctions:
    arguments:
      $countryProvider: '@TYPO3\CMS\Core\Country\CountryProvider'
    public: true

  Evoweb\StoreFinder\Hooks\TceMainListener:
    public: true

  Evoweb\StoreFinder\Middleware\StoreFinderMiddleware:
    public: true

  Evoweb\StoreFinder\Service\CacheService:
    public: true

  Evoweb\StoreFinder\Service\GeocodeService:
    public: true

  SJBR\StaticInfoTables\Domain\Repository\TerritoryRepository:
    public: true

  SJBR\StaticInfoTables\Domain\Model\CountryZoneRepository:
    public: true
